config/routes.rb
Rails.application.routes.draw do
  root 'posts#index'
  get 'login' => 'sessions#new', as: 'login'
  post 'login' => 'sessions#create', as: 'sessions'
  get 'signup' => 'users#new', as: 'signup'
  post 'signup' => 'users#create', as: 'users'
  get 'users' => 'users#index', as: 'users_list'
  get 'mypage' => 'users#mypage', as: 'mypage'
  get 'users/:id' => 'users#show', as: 'user'
  get 'posts' => 'posts#index', as: 'posts_list'
  get 'posts/new' => 'posts#new', as: 'new_post'
  post 'posts' => 'posts#create', as: 'posts'
  get 'posts/:id' => 'posts#show', as: 'post'
  delete 'logout' => 'sessions#destroy', as: 'logout'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  def user
    User.find_by(id: self.user_id)
  end

  def self.build(title="", body="")
    Post.new(title: title, body: body, user_id: self.user_id)
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  def posts
    Post.where(user_id: self.id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionsHelper
  before_action :current_user
  def login(user)
    session[:user_id] = user.id
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @post = Post.new
    @posts = Post.all
  end

  def show
    @post = Post.find(params[:id])
  end

  def create
    post = current_user.posts.build(post_params)
    if post.save
      redirect_to root_path
    else
      render :new
    end
  end

  private
    def post_params
      params.require(:post).permit(:title, :body)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      login user
      redirect_to root_path
    else
      render :new
    end
  end

  def destroy
    session.delete(:user_id)
    redirect_to login_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def index
    @users = User.all
  end

  def mypage

  end

  def show
    @user = User.find(params[:id])
  end

  def create
    user = User.new(user_params)
    if user.save
      login user
      redirect_to root_path
    else
      render :new
    end
  end

  private
    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def loged_in?
    !current_user.nil?
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PostApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= link_to 'Home', root_path %>
    <% if loged_in? %>
      <%= link_to 'ユーザー一覧', users_list_path %>
      <%= link_to '投稿一覧', posts_list_path %>
      <%= link_to 'マイページ', mypage_path %>
      <%= link_to 'ログアウト', logout_path, method: :delete %>
    <% else %>
      <%= link_to '会員登録', signup_path %>
      <%= link_to 'ログイン', login_path %>
    <% end %>
    
    <%= yield %>
  </body>
</html>

app/views/posts/index.html.erb
<h1>Posts#index</h1>
<p>Find me in app/views/posts/index.html.erb</p>
<% if loged_in? %>
  <%= form_for @post, url: posts_path do |f| %>
    <%= f.label :title %><br>
    <%= f.text_field :title %><br>
    <%= f.label :body %><br>
    <%= f.text_area :body %><br>
    <%= f.submit %>
  <% end %>
<% else %>
  <%= link_to 'ログイン', login_path %>
<% end %>

<% @posts.each do |post| %>
  <p><%= link_to post.title, post_path(post) %> | <%= post.created_at %> | <%= post.user.name %>さんの投稿</p>
<% end %>

app/views/posts/show.html.erb
<br>
タイトル：<%= @post.title %>
投稿者：<%= @post.user.name %>
投稿日時：<%= @post.created_at %>
本文：<%= @post.body %>

app/views/users/index.html.erb
<h1>ユーザー一覧</h1>

<% @users.each do |user| %>
  <p><%= link_to user.name, user_path(user) %> | 投稿数： <%= user.posts.count %></p>
<% end %>

app/views/users/mypage.html.erb
<h1><%= current_user.name %>さんのマイページ</h1>

<h2>今までの投稿一覧 <%= current_user.posts.count %>件</h2>
<% current_user.posts.each do |post| %>
  <p><%= link_to post.title, post_path(post) %> | <%= post.created_at %></p>
  <br>
<% end %>

app/views/users/new.html.erb
<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>
<%= form_for @user, url: users_path do |f| %>
  <%= f.label :name %><br>
  <%= f.text_field :name %><br>
  <%= f.label :email %><br>
  <%= f.text_field :email %><br>
  <%= f.label :password %><br>
  <%= f.password_field :password %><br>
  <%= f.label :password_confirmation %><br>
  <%= f.password_field :password_confirmation %><br>
  <%= f.submit %>
<% end %>

app/views/users/show.html.erb
<h1><%= @user.name %>さんのページ</h1>

<h2>今までの投稿一覧 <%= @user.posts.count %>件</h2>
<% @user.posts.each do |post| %>
  <p><%= link_to post.title, post_path(post) %> | <%= post.created_at %></p>
<% end %>